meshing_plugin_name: "godel_noether::NoetherMesher"
blend_tool_planning_plugin_name: "godel_noether::NoetherPathPlanner"
scan_tool_planning_plugin_name: "path_planning_plugins::openveronoi::ScanPlanner"
